# This is a basic workflow to help you get started with Actions

name: Pack extension

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Pack extension
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/upload-artifact@v1
      with:
        name: minivault-extension
        path: extension
