# This is a basic workflow to help you get started with Actions

name: Deploy to s3

on:
  push:
    branches: [ artifact ]

jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Copy files to S3 with the AWS CLI
      run: |
        aws s3 cp --recursive extension/ s3://mrboots.me/minivault/

    - name: Packing extension to stores
      run: |
        cd extension
        zip -vrFS ../minivault.zip ./*

    - uses: actions/upload-artifact@v1
      with:
        name: minivault.zip
        path: minivault.zip
