# This is a basic workflow to help you get started with Actions

name: Pack extension
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ * ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    steps:
    - name: Testing version with node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test

    steps:
    - name: Pack extension
      uses: actions/upload-artifact@v1
      with:
        name: minivault-extension
        path: extension
