# This is a basic workflow to help you get started with Actions

name: Test code
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]

jobs:
  testcode:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Testing version with node ${{ matrix.node-version }}
    - run: docker run --rm --cap-add=SYS_ADMIN -v "$PWD/test:/test" -v "$PWD/extension:/extension" --name minivault-puppeteer minivault/puppeteer:3.0.2 npm test

    - name: Pack extension
      uses: actions/upload-artifact@v1
      with:
        name: minivault-extension
        path: extension
