# This is a basic workflow to help you get started with Actions

name: Test code
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]

jobs:
  testcode:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run tests
      run: docker run --rm minivault/minivault npm test

    - name: Pack extension
      uses: actions/upload-artifact@v1
      with:
        name: minivault-extension
        path: extension
